# Load the test_phenos.csv file and generate some statistics

library(data.table)

# Input phenotype file generated by prepare_phenotypes.R
pheno.file <- "test_phenos.csv"

# If blank, output file will be your pheno.file name plus '_statistics', such as "test_phenos_statistics.csv"
out.file <- "" 

# variables to include in the table, change as specified in the analysis plan
stats <- c("sex", "chol_med", "age", "hdl_orig", "hdl", "tg_orig", "tg", "ldl")

# list the dichotomous lifestyle variables here to stratify the statistics
lifestyle.vars <- c("stst", "ltst") # if set to 'c()', data will not be stratified

# Load data
d <- fread(pheno.file, data.table=FALSE)

get.stats <- function(dat, stats) {
    out <- data.frame(Variable=stats, N=NA, Mean=NA, SD=NA, 
		      Median=NA, Min=NA, Max=NA, stringsAsFactors=FALSE)
    for (v in stats) {
	i <- which(stats==v)
	x <- na.omit(dat[,v])
        if (all(x %in% c(0,1))) {
	    out$N[i] <- sum(x)
	    out$Mean[i] <- mean(x)
	} else {
	    out$N[i] <- length(x)
	    out$Mean[i] <- mean(x)
	    out$SD[i] <- sd(x)
	    out$Median[i] <- median(x)
	    out$Min[i] <- min(x)
	    out$Max[i] <- max(x)
	}
    }
    return(out)
}

# levels of population group stratification, by order of decreasing sample size
group.levels <- names(sort(table(d$pop), decreasing=TRUE))

# helper function to prepare data
list.strata <- function(df, vars) {
	n.strata <- length(vars)*2 + 1
	if (n.strata == 1) {
		# If no variables to stratify return full non-missing data
		return(df[!is.na(df$gPC1),])
	} else {
		res <- vector(mode="list", length=n.strata)
		res.i <- 1
		# first strata are each lifestyle variable (2 levels)
		for (v in vars) {
		    for (i in c(1,0)) {
			res[[res.i]] <- df[df$related==FALSE & !is.na(df$gPC1) & !is.na(df[,v]) & df[,v]==i, ]
			res.i <- res.i+1
		    }
		}
		# final stratum is the 'total' group
		# using eval(parse(str)) to account for varying numbers of lifestyle variables
		str <- paste0("df[df$related==FALSE & !is.na(df$gPC1) & (", paste0("!is.na(df$",vars,")", collapse=" | "), "),]")
		res[[res.i]] <- eval(parse(text=str))
		return(res)
	}
}

# each object in the list is a statistic table for one of the groups
stats.list.by.group <- 
	lapply(group.levels, 
		      function(g) {
			# collect statistics for each lifestyle trait variable and all samples
			x <- d[d$pop == g,]
			stats.list <- lapply(list.strata(x, lifestyle.vars),
			                     function(dat) get.stats(dat, stats))

			# label each table in the list before combining
			if (length(lifestyle.vars)>0) {
				prefixes <- c(paste0(rep(toupper(lifestyle.vars),each=2),c("1.","0.")), "ALL.")
			} else {
				prefixes <- "ALL."
			}
			for (i in 1:length(stats.list)) {
			    names(stats.list[[i]])[-1] <- paste0(prefixes[i], names(stats.list[[i]])[-1])
			}
				
			# combine tables in the style of the analysis plan descriptive statistics table
			stats.table <- Reduce(function(x,y) merge(x, y, by="Variable", sort=FALSE), stats.list)
			stats.table <- cbind(Group=rep(g, nrow(stats.table)), stats.table)
			return(stats.table)
	      })

# combine all the individual tables together
out.table <- do.call("rbind", stats.list.by.group)

# save the data
if (out.file == "") out.file <- sub(".csv$", "_statistics.csv", pheno.file)
write.csv(out.table, out.file, row.names=F)


